---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Upgrade apt
  sudo: yes
  apt: upgrade=yes

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - libcurl4-openssl-dev
    - build-essential
    - git
